PROJECTNAME = Chip8
OUTPUT_DIR = out

INCLUDE_DIRS = -I include/SDL2 -Iinclude/imgui -Iinclude
LIB_DIRS = -L lib

ARGS = -Wall -Wextra -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic

LIBS = -lmingw32 -lSDL2main -lSDL2

SRC = $(wildcard src/*.cpp)  $(wildcard imgui/*.cpp) $(wildcard imgui/*.c)

default:
	g++ $(SRC) -o $(OUTPUT_DIR)/$(PROJECTNAME) $(ARGS) $(INCLUDE_DIRS) $(LIB_DIRS) $(LIBS)  